POST https://node-do-zero-p48c.onrender.com/videos
Content-Type: application/json

{
    "title":"video node2",
    "description":"Esse é o primeiro video",
    "duration":180
}

###

GET https://node-do-zero-p48c.onrender.com/videos

###

PUT https://node-do-zero-p48c.onrender.com/videos/17e67992-433f-406a-a5ad-efec3486e6c1
Content-Type: application/json

{
    "title":"video 07",
    "description":"Esse é o primeiro video",
    "duration":180
}

###
DELETE https://node-do-zero-p48c.onrender.com/videos/17e67992-433f-406a-a5ad-efec3486e6c1